#include "display-signal-message.h"
#include "handle-exit.h"
#include "log-message.h"

/**
 * @file handle-exit.c
 * @brief Handle exit signal.
 *
 * @author Cloudgen Wong
 * @date 2023-06-06
 */

/**
 * @brief Handle exit signal.
 *
 * This function handles the exit signal and displays a message accordingly.
 *
 * @param sig The signal to be handled.
 *
 * @note #include <stdlib.h>, for exit
 *
 * @see display_signal_message
 * @see exit
 *
 * @return void
 *
 * @details This function is called when the program receives an exit signal. It displays a message indicating the type of signal received and exits the program.
 *
 * @date 2023-03-05
 * @author Cloudgen Wong
 */
void handle_exit(int sig) {
  display_signal_message(sig);
  log_message("====== State: .*MAIN_LOOP* -> *END*.......... ======");
  exit(0);
}

/**
 * @brief Set signal handlers for SIGINT and SIGTERM.
 * 
 * This function sets the signal handlers for the SIGINT and SIGTERM signals.
 * It assigns the signal handler function `handle_exit` to both signals.
 * This ensures that when either SIGINT (generated by pressing Ctrl+C) or SIGTERM
 * (termination signal) is received, the `handle_exit` function is invoked.
 * 
 * @return void
 *
 * @details The function uses the `signal` function from the signal.h header file
 * to assign the `handle_exit` function as the signal handler for SIGINT and SIGTERM.
 * The `handle_exit` function is responsible for handling the exit procedure when
 * either of these signals is received.
 *
 * @note This function requires the following include files:
 * @note #include <signal.h> // for signal, SIGINT, SIGTERM
 *
 * @see handle_exit() for the signal handler function.
 *
 * @author Cloudgen Wong
 * @date 2023-06-06
 */
void signal_exit() {
  signal(SIGINT, handle_exit);
  signal(SIGTERM, handle_exit);
}